name: 'my_project'
version: '1.0'
config-version: 2

profile: 'my_project'

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'

models:
  dbt_project:
    my_project:
      data_cleaning:
        +enabled: true
          cleaned_data:
            +enabled: true

