version: 1
disable_existing_loggers: False
formatters:
  detailed:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    level: INFO
  file:
    class: logging.FileHandler
    formatter: detailed
    filename: 'logs/scraping.log'
    level: INFO
loggers:
  __main__:
    handlers: [console, file]
    level: INFO
    propagate: False
root:
  handlers: [console, file]
  level: INFO